# yaml-language-server: $schema=https://json.schemastore.org/github-issue-config.json

blank_issues_enabled: false
contact_links:
  - name: ğŸ“– æŸ¥çœ‹è´¡çŒ®æŒ‡å—
    url: https://github.com/sansan0/mao-map#-é‚€ä½ å…±ç»˜å†å²ç”»å·
    about: æŸ¥çœ‹è¯¦ç»†çš„è´¡çŒ®æŒ‡å—å’Œæ•°æ®è§„èŒƒ
  - name: ğŸ’¬ äº¤æµè®¨è®º
    url: https://github.com/sansan0/mao-map/discussions
    about: éæ­£å¼è®¨è®ºã€æƒ³æ³•åˆ†äº«æˆ–ä¸€èˆ¬æ€§é—®é¢˜
